version: 2

models:
  - name: aggregated_price
    description: calculate median and average price for each equipment
    columns: 
      - name: PORT_ID 
      - name: REGION_ID
      - name: COUNTRY_CODE
      - name: SRC_PORT_ID 
      - name: DEST_PORT_ID
      - name: COMPANY_ID
      - name: SUPPLIER_ID
      - name: EQUIPMENT_ID 
      - name: DAY
      - name: AVG_PRICE_IN_USD
      - name: MEDIAN_PRICE_IN_USD
      - name: DQ_OK

        
      

    