version: 2

models:
  - name: stg_exchange_rates
    description: exchange stg_exchange_rates
    tests:
      - dbt_utils.expression_is_true:
          expression: "LENGTH(CURRENCY) == 3"
    columns:
      - name: DAY
        description: Day on which the exchange rate is valid
      - name: CURRENCY
        description: Three-letter currency code
      - name: RATE
        description: Exchange Rate for converting a price in a given currency to USD


      

        
