{{
    config (
        materialized = 'view',schema = 'final'
    )
}}


WITH PORT_REGION_DATA AS ( 

SELECT 
SD.SRC_PORT_ID, 
SP.PORT_NAME as SRC_PORT_NAME,
SR.REGION_NAME as SRC_REGION_NAME,
SD.DEST_PORT_ID ,
SP1.PORT_NAME as DEST_PORT_NAME,
SR2.REGION_NAME as DEST_REGION_NAME
FROM staging.stg_datapoints sd 
LEFT JOIN staging.stg_ports sp  ON SD.SRC_PORT_ID = SP.PORT_ID 
LEFT JOIN staging.stg_regions sr ON SP.REGION_ID = SR.REGION_ID 
LEFT JOIN staging.stg_ports sp1  ON SD.DEST_PORT_ID = SP1.PORT_ID 
LEFT JOIN staging.stg_regions sr2 ON SP1.REGION_ID = SR2.REGION_ID 
 ), 
 
 PRC_PRT_RG AS (
 
SELECT 

PRD.SRC_PORT_ID,
PRD.SRC_PORT_NAME,
PRD.SRC_REGION_NAME,
PRD.DEST_PORT_ID, 
PRD.DEST_PORT_NAME,
PRD.DEST_REGION_NAME,
AP.COMPANY_ID, 
AP.SUPPLIER_ID,
AP.EQUIPMENT_ID, 
AP.AVG_PRICE_IN_USD, 
AP.MEDIAN_PRICE_IN_USD, 
AP.DQ_OK

FROM final.aggregated_price ap 
LEFT JOIN PORT_REGION_DATA PRD ON AP.SRC_PORT_ID = PRD.SRC_PORT_ID 
AND AP.DEST_PORT_ID = PRD.DEST_PORT_ID ) 

SELECT * FROM PRC_PRT_RG
